# (sector, type, src, pages, title, level)
SEL = [
("fin","Product design","iimb","38","Credit platform for teenagers","Hard"),
("fin","Product design","iimb","55-56","Bank app for rural India","Hard"),
("fin","Product improvement","iimb","116-117","Improve your favourite UPI app","Medium"),
("fin","Product improvement","iimb","110-111","Fraud prevention in a mobile banking app","Medium"),
("fin","Metrics","iima","294","Promotions in Google Pay","Medium"),
("fin","Root cause analysis","iima","308","Android DAU drop in a banking app","Medium"),
("food","Product design","iima","269-271","Quick-commerce vendor management","Medium"),
("food","Product improvement","iimb","126-127","Improve Swiggy","Medium"),
("food","Metrics","iima","291-292","BigBasket success metrics","Medium"),
("food","Metrics","iimb","153","Swiggy: product metrics before an IPO","Hard"),
("food","Go-to-market","iima","280-282","Swiggy table reservations launch","Medium"),
("food","Root cause analysis","iimb","86-87","Zomato cancellations rise","Hard"),
("food","Root cause analysis","iimb","82-83","Zepto delivery-time breaches","Hard"),
("ecom","Product design","iimb","30-31","E-commerce for senior citizens","Medium"),
("ecom","Product improvement","iimb","107-108","AI for Myntra's app","Medium"),
("ecom","Metrics","iima","290","Facebook Marketplace metrics","Medium"),
("ecom","Root cause analysis","iima","309-310","Decline in cart additions","Medium"),
("ecom","Root cause analysis","iimb","70-71","Amazon return rate rises","Medium"),
("ecom","Pricing","iima","297","Amazon Prime: price-cut projection","Medium"),
("ecom","Pricing","iimb","94","Pricing Amazon Prime","Medium"),
("ecom","Pricing","iima","300-301","Vendor price negotiation","Medium"),
("ecom","Strategy","iimb","146","Stopping fake products on Instagram","Medium"),
("mob","Product design","iima","250-251","Ola for schoolkids","Medium"),
("mob","Product design","iimb","39-40","Uber for kids","Hard"),
("mob","Product improvement","iimb","96","Improve Uber","Easy"),
("mob","Product improvement","iimb","114-115","Improve Google Maps","Medium"),
("mob","Root cause analysis","iima","306","Spike in Uber ride cancellations","Medium"),
("mob","Root cause analysis","iimb","65","Google Maps ETA discrepancies","Easy"),
("mob","Go-to-market","iimb","151-152","MakeMyTrip enters Dubai","Hard"),
("soc","Product design","iimb","46-47","LinkedIn for blue-collar workers","Hard"),
("soc","Product improvement","iima","316","Facebook Reactions","Medium"),
("soc","Metrics","iima","288-289","Instagram creator commerce","Medium"),
("soc","Metrics","iima","295","WhatsApp in-app video playback","Medium"),
("soc","Metrics","iimb","154-155","Success metrics for Gmail","Medium"),
("soc","Strategy","iimb","149-150","Users moving from WhatsApp to Telegram","Medium"),
("str","Product design","iima","254-255","Podcasts on Spotify","Medium"),
("str","Product improvement","iima","317-318","BookMyShow engagement","Medium"),
("str","Product improvement","iimb","105-106","Improve Hotstar","Medium"),
("str","Product improvement","iimb","120-121","Improve YouTube","Medium"),
("str","Root cause analysis","iimb","80-81","Prime Video views fall","Hard"),
("str","Pricing","iima","298","JioSaavn family plan","Medium"),
("str","Pricing","iimb","92","JioSaavn family plan (second take)","Easy"),
("str","Pricing","iima","299","Netflix pricing strategy","Medium"),
("hl","Product design","iimb","50","AI assistant for doctors in small clinics","Hard"),
("hl","Product improvement","iimb","97","HealthifyMe engagement","Easy"),
("hl","Root cause analysis","iima","303-304","Duolingo engagement drop","Medium"),
("hl","Root cause analysis","iimb","78-79","Adobe LMS trial-to-paid conversion","Medium"),
("hl","Go-to-market","iima","278-279","Launching a social fitness product","Medium"),
("saas","Product design","iima","267-268","AI copilot for customer-support agents","Medium"),
("saas","Product improvement","iimb","128-129","Improve Microsoft PowerPoint","Hard"),
("saas","Metrics","iima","293","Measuring an AI email-summary feature","Medium"),
("saas","Root cause analysis","iima","313-314","Users abandoning an AI chatbot","Medium"),
("saas","Root cause analysis","iima","311-312","Low CRM adoption","Medium"),
("saas","Go-to-market","iima","283-284","Launching an AI sales assistant","Medium"),
("hw","Product design","iima","264-266","Samsung Galaxy Buds experience","Medium"),
("hw","Product design","iima","245-246","Increasing voter turnout","Medium"),
("hw","Pricing","iimb","93","Pricing an Apple smart speaker","Easy"),
("hw","Go-to-market","iima","285-286","Tata Group loyalty programme","Medium"),
]
GUESS = [
("iima","235","Instagram uploads per day in India","Medium"),
("iima","236","YouTube revenue per day","Medium"),
("iima","237-238","Zoom's daily server usage","Hard"),
("iima","239","Users of a food-delivery app in South America","Medium"),
("iima","240-241","Dark stores for 10-minute coverage of Ahmedabad","Hard"),
("iimb","136","WhatsApp chats in India per day","Easy"),
("iimb","137","Storage needed by Google Photos","Easy"),
("iimb","138","Uber drivers in Bengaluru","Easy"),
("iimb","139","Google Drive storage for Singapore","Easy"),
("iimb","140","Bikes needed for a bike-taxi company","Medium"),
("iimb","141","Google searches per second","Medium"),
("iimb","142","Swiggy orders per hour in India","Medium"),
("iimb","143","Google Meet calls per day","Medium"),
("iimb","144","Users of a Bhojpuri short-movie app","Hard"),
]
